#!/usr/bin/env python3

import networkx as nx

from load_thalean_graph import load_spec, build_graph


def quotient_by_pairs(G, pair_map):
    seen = set()
    classes = []
    owner = {}

    for v in sorted(G.nodes()):
        if v in seen:
            continue
        pair = tuple(sorted((v, pair_map[v])))
        seen.update(pair)
        idx = len(classes)
        classes.append(pair)
        for x in pair:
            owner[x] = idx

    Q = nx.Graph()
    Q.add_nodes_from(range(len(classes)))

    for u, v in G.edges():
        a, b = owner[u], owner[v]
        if a != b:
            Q.add_edge(a, b)

    return Q, classes, owner


def unique_distance_partner_map(G):
    dist = dict(nx.all_pairs_shortest_path_length(G))
    diam = nx.diameter(G)
    out = {}
    for v in G.nodes():
        far = [u for u, d in dist[v].items() if d == diam]
        if len(far) != 1:
            raise RuntimeError(
                f"vertex {v} has {len(far)} distance-{diam} partners"
            )
        out[v] = far[0]
    return out, diam


def lift_second_involution_to_T(G60, G30, owner30, b30):
    """
    Lift the involution b on G30 back to G60 by sending each vertex v in T
    to the unique vertex w lying over b(owner30[v]) that is NOT a(v),
    where a is the antipode on G60.

    This gives the natural second sheet flip on the 60-vertex graph.
    """
    a60, _ = unique_distance_partner_map(G60)

    fiber30_to_vertices60 = {}
    for v60, c30 in owner30.items():
        fiber30_to_vertices60.setdefault(c30, []).append(v60)

    for k in fiber30_to_vertices60:
        fiber30_to_vertices60[k] = sorted(fiber30_to_vertices60[k])

    b60 = {}

    for v in sorted(G60.nodes()):
        c = owner30[v]
        target_c = b30[c]
        target_fiber = fiber30_to_vertices60[target_c]

        # choose the target vertex that is not the antipode of v
        choices = [w for w in target_fiber if w != a60[v]]
        if len(choices) != 1:
            raise RuntimeError(
                f"could not lift second involution at v={v}: "
                f"target fiber={target_fiber}, antipode={a60[v]}, choices={choices}"
            )
        b60[v] = choices[0]

    return b60


def check_automorphism(G, phi):
    if len(set(phi.values())) != G.number_of_nodes():
        return False, "not bijective"

    for u, v in G.edges():
        if not G.has_edge(phi[u], phi[v]):
            return False, f"edge ({u},{v}) not preserved"
    return True, "ok"


def main():
    print("=" * 80)
    print("CHECK Z2 x Z2 FIBER ACTION ON THALEAN GRAPH")
    print("=" * 80)

    G60 = build_graph(load_spec())

    a60, diam60 = unique_distance_partner_map(G60)
    G30, classes30, owner30 = quotient_by_pairs(G60, a60)

    b30, diam30 = unique_distance_partner_map(G30)
    b60 = lift_second_involution_to_T(G60, G30, owner30, b30)

    print("G60 vertices:", G60.number_of_nodes())
    print("G60 edges   :", G60.number_of_edges())
    print("diam(T)     :", diam60)
    print("diam(G30)   :", diam30)
    print()

    # involution checks
    a_inv = all(a60[a60[v]] == v for v in G60.nodes())
    b_inv = all(b60[b60[v]] == v for v in G60.nodes())
    a_fix = all(a60[v] != v for v in G60.nodes())
    b_fix = all(b60[v] != v for v in G60.nodes())

    print("a involution          :", a_inv)
    print("a fixed-point-free    :", a_fix)
    print("b involution (lifted) :", b_inv)
    print("b fixed-point-free    :", b_fix)

    ok_a, msg_a = check_automorphism(G60, a60)
    ok_b, msg_b = check_automorphism(G60, b60)

    print("a automorphism        :", ok_a, msg_a)
    print("b automorphism        :", ok_b, msg_b)

    commute = all(a60[b60[v]] == b60[a60[v]] for v in G60.nodes())
    print("a and b commute       :", commute)

    # orbit structure under <a,b>
    seen = set()
    orbits = []

    for v in sorted(G60.nodes()):
        if v in seen:
            continue
        orb = sorted({v, a60[v], b60[v], a60[b60[v]]})
        for x in orb:
            seen.add(x)
        orbits.append(orb)

    print("orbit count under <a,b>:", len(orbits))
    print("orbit sizes histogram   :", {
        s: sum(1 for o in orbits if len(o) == s)
        for s in sorted({len(o) for o in orbits})
    })
    print("first 10 orbits         :", orbits[:10])

    if commute and ok_a and ok_b and a_inv and b_inv:
        print()
        print("CONCLUSION")
        print("-" * 80)
        print("The 60-vertex Thalean graph carries a commuting Z2 x Z2-style")
        print("fiber action generated by a and b, with 15 four-element orbits.")
        print("This is strong evidence that T is naturally a Z2^2-cover of G15.")
    else:
        print()
        print("CONCLUSION")
        print("-" * 80)
        print("The expected Z2 x Z2 fiber action was not fully confirmed.")
        print("Inspect the lifted map b on T more carefully.")

if __name__ == "__main__":
    main()
