#!/usr/bin/env python3
"""
compare_flag_candidate_c.py

Build the dodecahedral flag-quotient chamber graph generated by the two
downstairs branching moves induced by the upstairs words:

    s2 s1
    s1 s2

Then compare it to an existing 60-vertex graph loaded from an edge-list file.

Usage examples:
    python3 scripts/compare_flag_candidate_c.py artifacts/reports/chamber_graph_edges.txt
    python3 scripts/compare_flag_candidate_c.py reports/quotients/chamber_graph.edgelist

Expected input edge-list format:
    one undirected edge per line, e.g.
        0 17
        17 42
        5 9

If your existing graph is stored some other way, this script still exports the
candidate graph so you can inspect or adapt as needed.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Set, Tuple

import networkx as nx

Face = int
Slot = int
Side = int
Flag = Tuple[Face, Slot, Side]
Chamber = Tuple[Face, Slot]

MOD = 5

FACE_CYCLES: Dict[Face, List[Face]] = {
    0:  [3, 5, 7, 9, 11],
    1:  [2, 4, 6, 8, 10],
    2:  [1, 4, 3, 11, 10],
    4:  [1, 6, 5, 3, 2],
    6:  [1, 8, 7, 5, 4],
    8:  [1, 10, 9, 7, 6],
    10: [1, 2, 11, 9, 8],
    3:  [0, 11, 2, 4, 5],
    5:  [0, 3, 4, 6, 7],
    7:  [0, 5, 6, 8, 9],
    9:  [0, 7, 8, 10, 11],
    11: [0, 9, 10, 2, 3],
}

FACES = sorted(FACE_CYCLES.keys())

EDGE_BACKREF: Dict[Tuple[Face, Slot], Tuple[Face, Slot]] = {}
for f, cyc in FACE_CYCLES.items():
    for k, g in enumerate(cyc):
        j = FACE_CYCLES[g].index(f)
        EDGE_BACKREF[(f, k)] = (g, j)


def chamber_label(ch: Chamber) -> str:
    f, k = ch
    return f"{f}:{k}"


def chamber_of(flag: Flag) -> Chamber:
    f, k, _ = flag
    return (f, k)


def s0(flag: Flag) -> Flag:
    f, k, side = flag
    return (f, k, 1 - side)


def s1(flag: Flag) -> Flag:
    f, k, side = flag
    if side == 0:
        return (f, (k - 1) % MOD, 1)
    return (f, (k + 1) % MOD, 0)


def s2(flag: Flag) -> Flag:
    f, k, side = flag
    g, j = EDGE_BACKREF[(f, k)]
    return (g, j, 1 - side)


OPS: Dict[str, Callable[[Flag], Flag]] = {
    "s0": s0,
    "s1": s1,
    "s2": s2,
}


def apply_word(flag: Flag, word: Iterable[str]) -> Flag:
    x = flag
    for op_name in word:
        x = OPS[op_name](x)
    return x


CHAMBERS: List[Chamber] = [(f, k) for f in FACES for k in range(5)]


def reps(ch: Chamber) -> Tuple[Flag, Flag]:
    f, k = ch
    return (f, k, 0), (f, k, 1)


def branch(ch: Chamber, word: Iterable[str]) -> Set[Chamber]:
    return {chamber_of(apply_word(r, word)) for r in reps(ch)}


def move_s2s1(ch: Chamber) -> Set[Chamber]:
    # turn then cross
    return branch(ch, ["s1", "s2"])


def move_s1s2(ch: Chamber) -> Set[Chamber]:
    # cross then turn
    return branch(ch, ["s2", "s1"])


def build_candidate_c() -> nx.Graph:
    G = nx.Graph()
    G.add_nodes_from(CHAMBERS)

    for ch in CHAMBERS:
        nbrs = set()
        nbrs |= move_s2s1(ch)
        nbrs |= move_s1s2(ch)
        nbrs.discard(ch)
        for nb in nbrs:
            G.add_edge(ch, nb)

    return G


def chamber_graph_invariants(G: nx.Graph) -> Dict[str, object]:
    triangles = sum(nx.triangles(G).values()) // 3
    diam = nx.diameter(G) if nx.is_connected(G) else None
    degree_set = sorted({d for _, d in G.degree()})
    return {
        "vertices": G.number_of_nodes(),
        "edges": G.number_of_edges(),
        "degree_set": degree_set,
        "connected": nx.is_connected(G),
        "triangles": triangles,
        "diameter": diam,
    }


def shell_profile(G: nx.Graph, src) -> List[int]:
    lengths = nx.single_source_shortest_path_length(G, src)
    maxd = max(lengths.values())
    return [sum(1 for d in lengths.values() if d == i) for i in range(maxd + 1)]


def export_graph(
    G: nx.Graph,
    out_edgelist: Path,
    out_labels_json: Path,
) -> Dict[str, int]:
    """
    Export with integer node IDs 0..59 and save a chamber label map.
    """
    node_order = sorted(G.nodes())
    node_to_id = {node: i for i, node in enumerate(node_order)}

    H = nx.Graph()
    H.add_nodes_from(range(len(node_order)))
    for u, v in G.edges():
        H.add_edge(node_to_id[u], node_to_id[v])

    out_edgelist.parent.mkdir(parents=True, exist_ok=True)
    nx.write_edgelist(H, out_edgelist, data=False)

    import json
    label_map = {
        str(node_to_id[node]): {
            "face": node[0],
            "slot": node[1],
            "label": chamber_label(node),
            "adjacent_face": FACE_CYCLES[node[0]][node[1]],
        }
        for node in node_order
    }
    with out_labels_json.open("w", encoding="utf-8") as f:
        json.dump(label_map, f, indent=2, sort_keys=True)

    return node_to_id


def read_existing_graph(path: Path) -> nx.Graph:
    G = nx.read_edgelist(path, nodetype=int)
    # normalize to simple graph with integer labels
    H = nx.Graph()
    H.add_nodes_from(G.nodes())
    H.add_edges_from(G.edges())
    return H


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "existing_graph",
        nargs="?",
        help="Path to existing graph edge-list file for isomorphism comparison.",
    )
    parser.add_argument(
        "--outdir",
        default="artifacts/reports/flag_compare",
        help="Directory for exported candidate graph artifacts.",
    )
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    candidate = build_candidate_c()
    inv = chamber_graph_invariants(candidate)

    print("=" * 80)
    print("CANDIDATE_C FROM FLAG GEOMETRY")
    print("=" * 80)
    for k, v in inv.items():
        print(f"{k:>10}: {v}")
    print()
    sample = (7, 0)
    print(f"sample shell from {sample}: {shell_profile(candidate, sample)}")
    print()

    exported_edgelist = outdir / "candidate_c_flag_graph.edgelist"
    exported_labels = outdir / "candidate_c_flag_graph_labels.json"
    export_graph(candidate, exported_edgelist, exported_labels)

    print(f"Exported candidate edge-list: {exported_edgelist}")
    print(f"Exported chamber label map:   {exported_labels}")
    print()

    if args.existing_graph:
        existing_path = Path(args.existing_graph)
        existing = read_existing_graph(existing_path)
        existing_inv = chamber_graph_invariants(existing)

        print("=" * 80)
        print("EXISTING GRAPH")
        print("=" * 80)
        for k, v in existing_inv.items():
            print(f"{k:>10}: {v}")
        print()

        iso = nx.is_isomorphic(candidate, existing)
        print("=" * 80)
        print("ISOMORPHISM TEST")
        print("=" * 80)
        print(f"isomorphic: {iso}")

        if iso:
            gm = nx.algorithms.isomorphism.GraphMatcher(candidate, existing)
            mapping = next(gm.isomorphisms_iter())
            # mapping: candidate chamber tuple -> existing integer node
            preview = list(mapping.items())[:10]
            print()
            print("sample mapping entries (candidate chamber -> existing node):")
            for left, right in preview:
                print(f"  {left} -> {right}")

            mapping_path = outdir / "candidate_to_existing_mapping.txt"
            with mapping_path.open("w", encoding="utf-8") as f:
                for left, right in sorted(mapping.items(), key=lambda x: x[1]):
                    f.write(f"{left[0]}:{left[1]} -> {right}\n")
            print()
            print(f"Saved full mapping: {mapping_path}")


if __name__ == "__main__":
    main()
