#!/usr/bin/env python3

import sys
from pathlib import Path
from collections import deque
import networkx as nx

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hyperxi.transport.coxeter_generators import F, S

G6_PATH = ROOT / "artifacts/census/thalion_graph.g6"


def load_graph():
    g6 = G6_PATH.read_text(encoding="utf-8").strip()
    G = nx.from_graph6_bytes(g6.encode())
    return nx.convert_node_labels_to_integers(G)


def antipode_map(G):
    diam = nx.diameter(G)
    dists = dict(nx.all_pairs_shortest_path_length(G))
    amap = {}
    for v in G.nodes():
        far = [u for u, d in dists[v].items() if d == diam]
        if len(far) != 1:
            raise ValueError(f"vertex {v} has {len(far)} distance-{diam} partners")
        amap[v] = far[0]
    return diam, amap


def build_perm(n, fn):
    return tuple(fn(i) for i in range(n))


def compose(p, q):
    return tuple(p[q[i]] for i in range(len(p)))


def perm_from_map(n, mapping):
    return tuple(mapping[i] for i in range(n))


def inverse(p):
    q = [None] * len(p)
    for i, j in enumerate(p):
        q[j] = i
    return tuple(q)


def main():
    G = load_graph()
    n = G.number_of_nodes()

    print("=" * 80)
    print("THALEAN ANTIPODE WORD SEARCH")
    print("=" * 80)
    print("vertices:", n)
    print("edges:", G.number_of_edges())
    print()

    diam, amap = antipode_map(G)
    A = perm_from_map(n, amap)

    print("diameter:", diam)
    print("antipode involution:", compose(A, A) == tuple(range(n)))
    print()

    pF = build_perm(n, F)
    pS = build_perm(n, S)

    print("GENERATOR SANITY")
    print("-" * 80)
    print("F is permutation:", sorted(pF) == list(range(n)))
    print("S is permutation:", sorted(pS) == list(range(n)))
    print()

    gens = {
        "F": pF,
        "S": pS,
        "f": inverse(pF),
        "s": inverse(pS),
    }

    max_len = 14
    ident = tuple(range(n))
    seen = {ident: ""}
    q = deque([ident])

    found_exact = []

    while q:
        p = q.popleft()
        w = seen[p]

        if p == A:
            found_exact.append(w)

        if len(w) >= max_len:
            continue

        for gname, gperm in gens.items():
            newp = compose(gperm, p)
            if newp not in seen:
                seen[newp] = w + gname
                q.append(newp)

    print("search depth:", max_len)
    print("words searched:", len(seen))
    print()

    print("EXACT MATCHES")
    print("-" * 80)
    if found_exact:
        for w in sorted(found_exact, key=len):
            print(f"word={w!r}  length={len(w)}")
    else:
        print("No exact word found up to this depth.")
    print()

    fam = {
        "S": pS,
        "F": pF,
        "FS": compose(pF, pS),
        "SF": compose(pS, pF),
        "F2": compose(pF, pF),
        "S2": compose(pS, pS),
        "FSF": compose(pF, compose(pS, pF)),
        "SFS": compose(pS, compose(pF, pS)),
        "FSFS": compose(pF, compose(pS, compose(pF, pS))),
        "SFSF": compose(pS, compose(pF, compose(pS, pF))),
    }

    print("CANDIDATE CHECKS")
    print("-" * 80)
    for name, perm in fam.items():
        print(f"{name:>5}  matches antipode: {perm == A}")
    print()

    print("INTERPRETATION")
    print("-" * 80)
    if found_exact:
        print("A transport word realizes the antipode map exactly.")
        print("So the far-partner involution is not only metric but also generated by transport.")
    else:
        print("No short word in F,S realizes the antipode map at this search depth.")
        print("The antipode may still be generated by a longer word or by a more natural composite operator.")


if __name__ == "__main__":
    main()
